### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by indifferentghost** [canjs/can-stache-route-helpers#15]
## can-route-stache-handlers.html
- [x] codepen
- [x] reformatted to prevent `@codepen` from bugging the next lines into a `code-toolbar` that breaks away from the list item.

## can-stache-route-helpers.routeCurrent.html
- [x] codepen
  - [x] Questioning the relevance of having codepen for stache helpers. Instead made comment.
- [x] `@description`
- [x] indentation
- [x] moved use example to signature
- [x] demo doesn't seem to be working.

##### discourse:
- [x] [{{# routeCurrent([subsetMatch,] hashes...) }}FN{{else}}INVERSE{{/ routeCurrent }}]
(https://canjs.com/doc/can-stache-route-helpers.routeCurrent.html#___routeCurrent__subsetMatch__hashes______FN__else__INVERSE___routeCurrent__) Lengthy title forces indent menu bar.

![menu break](https://user-images.githubusercontent.com/12449668/47932012-a8e2f000-de8d-11e8-88dd-9819fdbc5695.gif)

## can-stache-route-helpers.routeUrl.html
- [x] codepen
 - [x] Questioning the relevance of having codepen for stache helpers. Instead made comment.
- [x] `@description`
- [x] indentation
- [x] moved use example to signature
- [x] added @params to first signature
- [x] demo doesn't seem to be working.

**Comment by chasenlehara** [comment]
This looks complete. I’m going to close it.
