### ISSUE TITLE
Improve the can-stache/helpers/route docs

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-stache-route-helpers#5]
@chasenlehara commented on [Thu Dec 01 2016](https://github.com/canjs/can-stache/issues/120)

They’re pretty bare-bones right now: https://v3.canjs.com/doc/can-stache/helpers/route.html

**Comment by phillipskevin** [comment]
These docs were improved in https://github.com/canjs/can-stache-route-helpers/pull/2. Going to close this.
